# Check https://circleci.com/docs/2.0/language-php/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.0-node
      - image: docker.elastic.co/elasticsearch/elasticsearch:5.6.13

    working_directory: ~/repo

    environment:
      - SYMFONY_DEPRECATIONS_HELPER: weak_vendors
      - SYMFONY_ENV: test

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: cp app/config/parameters.travis.yml app/config/parameters.yml
      - run: composer install -n --prefer-dist
      - run: yarn install && yarn build
      - run: php app/console doctrine:schema:update --force
  
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
        
      # run tests!
      - run: php app/console lint:yaml app/config
      - run: php app/console lint:twig app/Resources
      - run: php app/console doctrine:schema:update --force
      - run: php bin/simple-phpunit
      - run: php bin/behat