<?php

namespace Acts\CamdramInfobaseBundle\Entity;

/**
 * ArticleTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleTagRepository extends \Doctrine\ORM\EntityRepository
{
    public function findWithCountSortedByCount()
    {
        $query = $this->createQueryBuilder('t')
            ->innerJoin('t.articles', 'a')#
            ->select('t AS tag')
            ->addSelect('COUNT(a) AS num_articles')
            ->groupBy('t')
            ->orderBy('num_articles', 'DESC')
            ->getQuery();

        $res = $query->getResult();

        return $res;
    }

    public function findWithCountSortedByName($limit)
    {
        $query = $this->createQueryBuilder('t')
            ->innerJoin('t.articles', 'a')#
            ->select('t AS tag')
            ->addSelect('COUNT(a) AS num_articles')
            ->groupBy('t')
            ->orderBy('t.name')
            ->setMaxResults($limit)
            ->getQuery();

        $res = $query->getResult();

        return $res;
    }

    public function findRelated(ArticleTag $tag, $limit)
    {
        $query = $this->createQueryBuilder('t')
            ->innerJoin('t.articles', 'a')
            ->innerJoin('a.tags', 's')
            ->groupBy('t')
            ->select('t AS tag')
            ->addSelect('COUNT(t) as num')
            ->where('s = :tag')
            ->andWhere('t != :tag')
            ->setParameter('tag', $tag)
            ->orderBy('num', 'DESC')
            ->setMaxResults($limit)
            ->getQuery();

        return $query->getResult();
    }
}
