<?php

namespace Acts\CamdramInfobaseBundle\Entity;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findRecentlyUpdated($limit)
    {
        return $this->createQueryBuilder('a')
            ->where('a.createdAt != a.updatedAt')
            ->orderBy('a.updatedAt', 'DESC')
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }

    public function findRecentlyCreated($limit)
    {
        return $this->createQueryBuilder('a')
            ->orderBy('a.createdAt', 'DESC')
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }

    public function findRelated(Article $article, $limit)
    {
        $query = $this->createQueryBuilder('a')
            ->innerJoin('a.tags', 't')
            ->innerJoin('t.articles', 'b')
            ->groupBy('a')
            ->select('a AS article')
            ->addSelect('COUNT(a) as num')
            ->where('b = :article')
            ->andWhere('a != :article')
            ->setParameter('article', $article)
            ->orderBy('num', 'DESC')
            ->addOrderBy('a.name')
            ->setMaxResults($limit)
            ->getQuery();

        return $query->getResult();
    }
}
