<?php

namespace Acts\CamdramInfobaseBundle\Entity;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findRecentlyUpdated($limit)
    {
        return $this->createQueryBuilder('a')
            ->where('a.createdAt != a.updatedAt')
            ->orderBy('a.updatedAt', 'DESC')
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }

    public function findRecentlyCreated($limit)
    {
        return $this->createQueryBuilder('a')
            ->orderBy('a.createdAt', 'DESC')
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }

    public function findRelated(Article $article, $limit)
    {
        $query = $this->createQueryBuilder('related_article')
            ->innerJoin('related_article.tags', 'tags')
            ->innerJoin('tags.articles', 'this_article')
            ->groupBy('related_article')
            ->select('related_article AS article')
            ->addSelect('COUNT(related_article) as num')
            ->where('this_article = :article')
            ->andWhere('related_article != :article')
            ->setParameter('article', $article)
            ->orderBy('num', 'DESC')
            ->addOrderBy('related_article.name')
            ->setMaxResults($limit)
            ->getQuery();

        return $query->getResult();
    }
}
