<?php

namespace Acts\CamdramInfobaseBundle\Entity;

/**
 * ArticleRevisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRevisionRepository extends \Doctrine\ORM\EntityRepository
{
}
